<?php

declare(strict_types=1);

namespace venndev\plugin\items;

use pocketmine\entity\Entity;
use pocketmine\player\Player;
use pocketmine\utils\TextFormat;
use venndev\plugin\item\tools\Pickaxe;
use venndev\plugin\item\Weapon;

class DivanDrill extends Pickaxe
{

    public function getName() : string
    {
        return TextFormat::AQUA . "Divan's Drill";
    }

    public function getRecipeName() : string
    {
        return "divan_drill";
    }

    public function getNameVanilla() : string
    {
        return "prismarine_shard";
    }

    public function getPower(): int
    {
        return 10; // TODO: Change the autogenerated stub
    }

    public function getLore() : array
    {
        return [
            TextFormat::GRAY . "A drill by Divan."
        ];
    }

    public function getMiningSpeed(): float
    {
        return 1800.0;
    }

}